const {
    IAuthPayload,
    IAuthDocument,
    IAuthBuyerMessageDetails,
    IEmailMessageDetails,
    IAuth,
    ISignUpPayload,
    ISignInPayload,
    IForgotPassword,
    IResetPassword,
    IReduxAuthPayload,
    IReduxAddAuthUser,
    IReduxLogout,
    IAuthResponse,
    IAuthUser,
} = require('./auth.interface');
const { IBuyerDocument, IReduxBuyer } = require('./buyer.interface');
const {
    IConversationDocument,
    IMessageDocument,
    IMessageDetails,
    IChatBoxProps,
    IChatSellerProps,
    IChatBuyerProps,
    IChatMessageProps,
} = require('./chat.interface');
const {
    GigType,
    ICreateGig,
    ISellerGig,
    IGigContext,
    IGigsProps,
    IGigCardItems,
    ISelectedBudget,
    IGigViewReviewsProps,
    IGigInfo,
    IGigTopProps,
} = require('./gig.interface');
const {
    IOrderNotifcation,
    IOffer,
    IExtendedDelivery,
    IDeliveredWork,
    IOrderEvents,
    IOrderReview,
    IOrderMessage,
    IOrderDocument,
} = require('./order.interface');
const {
    IReviewMessageDetails,
    IRatingTypes,
    IRatingCategories,
    IRatingCategoryItem,
    IReviewDocument,
} = require('./review.interface');
const {
    ISearchResult,
    IHitsTotal,
    IQueryList,
    IQueryString,
    ITerm,
    IPaginateProps,
} = require('./search.interface');
const {
    SellerType,
    ILanguage,
    IExperience,
    IEducation,
    ICertificate,
    ISellerDocument,
} = require('./seller.interface');
const { IEmailLocals } = require('./email.interface');
const {
    IErrorResponse,
    IError,
    ErrnoException,
} = require('./error-handler-interface');

const { uploads, videoUpload } = require('./cloudinary-upload');
const {
    CustomError,
    BadRequestError,
    NotFoundError,
    NotAuthorizedError,
    FileTooLargeError,
    ServerError,
} = require('./error-handler');
const { verifyGatewayRequest } = require('./gateway-middleware');
const { winstonLogger } = require('./logger');
// const {
//     firstLetterUppercase,
//     lowerCase,
//     toUpperCase,
//     isEmail,
//     isDataURL,
// } = require('./helpers');

module.exports = {
    IAuthPayload,
    IAuthDocument,
    IAuthBuyerMessageDetails,
    IEmailMessageDetails,
    IAuth,
    ISignUpPayload,
    ISignInPayload,
    IForgotPassword,
    IResetPassword,
    IReduxAuthPayload,
    IReduxAddAuthUser,
    IReduxLogout,
    IAuthResponse,
    IAuthUser,
    IBuyerDocument,
    IReduxBuyer,
    IConversationDocument,
    IMessageDocument,
    IMessageDetails,
    IChatBoxProps,
    IChatSellerProps,
    IChatBuyerProps,
    IChatMessageProps,
    GigType,
    ICreateGig,
    ISellerGig,
    IGigContext,
    IGigsProps,
    IGigCardItems,
    ISelectedBudget,
    IGigViewReviewsProps,
    IGigInfo,
    IGigTopProps,
    IOrderNotifcation,
    IOffer,
    IExtendedDelivery,
    IDeliveredWork,
    IOrderEvents,
    IOrderReview,
    IOrderMessage,
    IOrderDocument,
    IReviewMessageDetails,
    IRatingTypes,
    IRatingCategories,
    IRatingCategoryItem,
    IReviewDocument,
    ISearchResult,
    IHitsTotal,
    IQueryList,
    IQueryString,
    ITerm,
    IPaginateProps,
    SellerType,
    ILanguage,
    IExperience,
    IEducation,
    ICertificate,
    ISellerDocument,
    IEmailLocals,
    IErrorResponse,
    IError,

    uploads,
    videoUpload,
    ErrnoException,
    CustomError,
    BadRequestError,
    NotFoundError,
    NotAuthorizedError,
    FileTooLargeError,
    ServerError,
    verifyGatewayRequest,
    winstonLogger,
    firstLetterUppercase,
    lowerCase,
    toUpperCase,
    isEmail,
    isDataURL,
};
