export const {
    IAuthPayload,
    IAuthDocument,
    IAuthBuyerMessageDetails,
    IEmailMessageDetails,
    IAuth,
    ISignUpPayload,
    ISignInPayload,
    IForgotPassword,
    IResetPassword,
    IReduxAuthPayload,
    IReduxAddAuthUser,
    IReduxLogout,
    IAuthResponse,
    IAuthUser,
} = require('./auth.interface');
export const { IBuyerDocument, IReduxBuyer } = require('./buyer.interface');
export const {
    IConversationDocument,
    IMessageDocument,
    IMessageDetails,
    IChatBoxProps,
    IChatSellerProps,
    IChatBuyerProps,
    IChatMessageProps,
} = require('./chat.interface');
export const {
    GigType,
    ICreateGig,
    ISellerGig,
    IGigContext,
    IGigsProps,
    IGigCardItems,
    ISelectedBudget,
    IGigViewReviewsProps,
    IGigInfo,
    IGigTopProps,
} = require('./gig.interface');
export const {
    IOrderNotifcation,
    IOffer,
    IExtendedDelivery,
    IDeliveredWork,
    IOrderEvents,
    IOrderReview,
    IOrderMessage,
    IOrderDocument,
} = require('./order.interface');
export const {
    IReviewMessageDetails,
    IRatingTypes,
    IRatingCategories,
    IRatingCategoryItem,
    IReviewDocument,
} = require('./review.interface');
export const {
    ISearchResult,
    IHitsTotal,
    IQueryList,
    IQueryString,
    ITerm,
    IPaginateProps,
} = require('./search.interface');
export const {
    SellerType,
    ILanguage,
    IExperience,
    IEducation,
    ICertificate,
    ISellerDocument,
} = require('./seller.interface');
export const { IEmailLocals } = require('./email.interface');
export const {
    IErrorResponse,
    IError,
    ErrnoException,
} = require('./error-handler-interface');

export const { uploads, videoUpload } = require('./cloudinary-upload');
export const {
    CustomError,
    BadRequestError,
    NotFoundError,
    NotAuthorizedError,
    FileTooLargeError,
    ServerError,
} = require('./error-handler');
export const { verifyGatewayRequest } = require('./gateway-middleware');
export const { winstonLogger } = require('./logger');
export const {
    firstLetterUppercase,
    lowerCase,
    toUpperCase,
    isEmail,
    isDataURL,
} = require('./helpers');

// module.exports = {
//     IAuthPayload,
//     IAuthDocument,
//     IAuthBuyerMessageDetails,
//     IEmailMessageDetails,
//     IAuth,
//     ISignUpPayload,
//     ISignInPayload,
//     IForgotPassword,
//     IResetPassword,
//     IReduxAuthPayload,
//     IReduxAddAuthUser,
//     IReduxLogout,
//     IAuthResponse,
//     IAuthUser,
//     IBuyerDocument,
//     IReduxBuyer,
//     IConversationDocument,
//     IMessageDocument,
//     IMessageDetails,
//     IChatBoxProps,
//     IChatSellerProps,
//     IChatBuyerProps,
//     IChatMessageProps,
//     GigType,
//     ICreateGig,
//     ISellerGig,
//     IGigContext,
//     IGigsProps,
//     IGigCardItems,
//     ISelectedBudget,
//     IGigViewReviewsProps,
//     IGigInfo,
//     IGigTopProps,
//     IOrderNotifcation,
//     IOffer,
//     IExtendedDelivery,
//     IDeliveredWork,
//     IOrderEvents,
//     IOrderReview,
//     IOrderMessage,
//     IOrderDocument,
//     IReviewMessageDetails,
//     IRatingTypes,
//     IRatingCategories,
//     IRatingCategoryItem,
//     IReviewDocument,
//     ISearchResult,
//     IHitsTotal,
//     IQueryList,
//     IQueryString,
//     ITerm,
//     IPaginateProps,
//     SellerType,
//     ILanguage,
//     IExperience,
//     IEducation,
//     ICertificate,
//     ISellerDocument,
//     IEmailLocals,
//     IErrorResponse,
//     IError,

//     uploads,
//     videoUpload,
//     ErrnoException,
//     CustomError,
//     BadRequestError,
//     NotFoundError,
//     NotAuthorizedError,
//     FileTooLargeError,
//     ServerError,
//     verifyGatewayRequest,
//     winstonLogger,
//     firstLetterUppercase,
//     lowerCase,
//     toUpperCase,
//     isEmail,
//     isDataURL,
// };
